// iron-web-client/src/app/session/session.component.ts
﻿import {Component} from "@angular/core";
import {Session} from "../../models/session";
import {SessionService} from "../services/session.service";

@Component({
  selector: 'app-session',
  templateUrl: 'session.component.html',
  styleUrls: ['session.component.scss']
})
export class SessionComponent {
  currentSession: Session;
  connected = false;

  constructor(public sessionService: SessionService) {
    this.sessionService.currentSession$.subscribe(session => this.currentSession = session);
  }
}

﻿<app-login *ngIf="!currentSession?.active"></app-login>
<app-screen-renderer *ngIf="currentSession?.active"></app-screen-renderer>

// iron-svelte-client/src/routes/session/+page.svelte
<script>
	import Login from '$lib/login/login.svelte';
	import RemoteScreen from '$lib/remote-screen/remote-screen.svelte';
	import { currentSession } from '../../services/session.service';

	let showLogin = true;
	
	currentSession.subscribe(v => {
		showLogin = !v.active
	});
</script>
	{#if showLogin}
		<Login />
	{/if}
	<RemoteScreen />
